version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=social_media_automator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
  
  web:
    image: social_media_automator:1.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  worker:
    image: social_media_automator:1.0.0
    command: celery -A main worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  

volumes:
  postgres_data: